version: 2.1

commands:
  build-and-test:
    description: "Install, build and test the library"
    steps:
      - run:
          name: "Install into environment"
          command: |
            poetry install
      - run:
          name: "Lint library and tests"
          command: |
            poetry run flake8 pymage_size

jobs:
  test-310:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - build-and-test
  test-39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - build-and-test

  deploy:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Publish
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
    version: 2

    test-workflow:
      jobs:
        - test-310
        - test-39

    deploy-workflow:
      jobs:
        - test-310:
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
        - test-39:
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
        - deploy:
            requires:
              - test-310
              - test-39
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
